/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Lampbert;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author <Mikel>
 */
public class Proceso extends javax.swing.JFrame implements Runnable {

    /**
     * Creates new form Proceso
     */
    int id;
    int tiempos[];
    Thread hilo;
    int interval;
    int indiceProceso;
    
    public Proceso(int id) {
        initComponents();
        this.id=id;
        this.idLabel.setText(this.id+"");
        tiempos=new int[10];
        this.indiceProceso=0;
        this.hilo= new Thread(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idLabel = new javax.swing.JLabel();
        num1 = new javax.swing.JLabel();
        num5 = new javax.swing.JLabel();
        num6 = new javax.swing.JLabel();
        num7 = new javax.swing.JLabel();
        num8 = new javax.swing.JLabel();
        num9 = new javax.swing.JLabel();
        num10 = new javax.swing.JLabel();
        num3 = new javax.swing.JLabel();
        num4 = new javax.swing.JLabel();
        num2 = new javax.swing.JLabel();
        intervalo = new javax.swing.JTextField();
        startProcess = new javax.swing.JButton();
        Mensaje = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        idLabel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        idLabel.setText("id");

        num1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        num1.setText("0");

        num5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        num5.setText("0");

        num6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        num6.setText("0");

        num7.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        num7.setText("0");

        num8.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        num8.setText("0");

        num9.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        num9.setText("0");

        num10.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        num10.setText("0");

        num3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        num3.setText("0");

        num4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        num4.setText("0");

        num2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        num2.setText("0");

        startProcess.setText("Comenzar");
        startProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startProcessActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(intervalo)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Mensaje)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 58, Short.MAX_VALUE)
                .addComponent(startProcess)
                .addGap(54, 54, 54))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(idLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(num2, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                    .addComponent(num1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(num3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(num4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(num5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(num6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(num7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(num8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(num9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(num10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(idLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(intervalo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(startProcess)
                .addGap(18, 18, 18)
                .addComponent(num1)
                .addGap(18, 18, 18)
                .addComponent(num2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(num3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(num4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(num5)
                .addGap(18, 18, 18)
                .addComponent(num6)
                .addGap(18, 18, 18)
                .addComponent(num7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(num8)
                .addGap(18, 18, 18)
                .addComponent(num9)
                .addGap(11, 11, 11)
                .addComponent(num10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(Mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startProcessActionPerformed
        try{
            this.interval = Integer.parseInt(this.intervalo.getText());
            for(int i=0;i<10;i++){
                this.tiempos[i]= this.interval*i;
            }
            actualizar();
            this.hilo.start();
        }catch(NumberFormatException w){
            
        }
    }//GEN-LAST:event_startProcessActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Proceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Proceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Proceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Proceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Proceso(0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Mensaje;
    private javax.swing.JLabel idLabel;
    private javax.swing.JTextField intervalo;
    private javax.swing.JLabel num1;
    private javax.swing.JLabel num10;
    private javax.swing.JLabel num2;
    private javax.swing.JLabel num3;
    private javax.swing.JLabel num4;
    private javax.swing.JLabel num5;
    private javax.swing.JLabel num6;
    private javax.swing.JLabel num7;
    private javax.swing.JLabel num8;
    private javax.swing.JLabel num9;
    private javax.swing.JButton startProcess;
    // End of variables declaration//GEN-END:variables

    private void actualizar() {
        this.num1.setText(this.tiempos[0]+"");
        this.num2.setText(this.tiempos[1]+"");
        this.num3.setText(this.tiempos[2]+"");
        this.num4.setText(this.tiempos[3]+"");
        this.num5.setText(this.tiempos[4]+"");
        this.num6.setText(this.tiempos[5]+"");
        this.num7.setText(this.tiempos[6]+"");
        this.num8.setText(this.tiempos[7]+"");
        this.num9.setText(this.tiempos[8]+"");
        this.num10.setText(this.tiempos[9]+"");
    }

    @Override
    public void run() {
        Thread currhilo = Thread.currentThread();
        while(currhilo==hilo){
            try {
                Thread.sleep(1500);
                for(int i=0;i<10 ;i++){
                    this.tiempos[i]+=this.interval;
                }
                actualizar();
            } catch (InterruptedException ex) {
                Logger.getLogger(Proceso.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    public int recibirMensaje(String mes,int indice, int val){
        int aux= this.tiempos[indice];
        if(this.tiempos[indice]<val){
            this.tiempos[indice]= val+=1;
            for(int i=indice+1;i<10;i++){
                this.tiempos[i]= this.tiempos[i-1]+ this.interval;
            }
            actualizar();
        }
        this.indiceProceso=indice;
        this.Mensaje.setText(mes);
        return aux;
    }
    public String enviarMensaje(){
        indiceProceso+=1;
        if(indiceProceso>9){
            this.indiceProceso=0;
            this.tiempos[0]=this.tiempos[this.tiempos.length-1]+this.interval;
            for(int i=1;i<10;i++){
                this.tiempos[i]= this.tiempos[i-1]+this.interval;
            }
            actualizar();
            return this.id+" "+this.Mensaje.getText()+" "+this.indiceProceso+" "+ this.tiempos[9];
        }else
        return this.id+"*"+this.Mensaje.getText()+"*"+this.indiceProceso+"*"+ this.tiempos[this.indiceProceso-1];
    }
}
